#!/bin/bash

sudo yum -y install epel-release wget
sudo yum -y update
sudo yum -y install java
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum -y install jenkins
sudo useradd jenkins
